use DBI;
use strict;
my $db='bank';
my $usr='postgres';
my $host='localhost';
my $port='5432';
my $pwd='445475';
my $connect_string="psql -h $host -p $port -d $db -U $usr";
open(file,"|$connect_string");
print file<<ENDOFPSQL;
set client_encoding=GBK;
create table "near_source_model_layer"."acct-06-30" as (select * from "technology_buffer_layer"."acct_06_30");
create table "near_source_model_layer"."acct-07-31" as (select * from "technology_buffer_layer"."acct_07_31");
create table "near_source_model_layer"."acct-08-31" as (select * from "technology_buffer_layer"."acct_08_31");
create table "near_source_model_layer"."card-06-30" as (select * from "technology_buffer_layer"."card_06_30");
create table "near_source_model_layer"."card-07-31" as (select * from "technology_buffer_layer"."card_07_31");
create table "near_source_model_layer"."card-08-31" as (select * from "technology_buffer_layer"."card_08_31");
create table "near_source_model_layer"."cust-06-30" as (select * from "technology_buffer_layer"."cust_06_30");
create table "near_source_model_layer"."cust-07-31" as (select * from "technology_buffer_layer"."cust_07_31");
create table "near_source_model_layer"."cust-08-31" as (select * from "technology_buffer_layer"."cust_08_31");

UPDATE "near_source_model_layer"."acct-06-30" SET "last_cons_post_date"=null WHERE "last_cons_post_date"=''; 
UPDATE "near_source_model_layer"."acct-06-30" SET "last_cash_post_date"=null WHERE "last_cash_post_date"=''; 
UPDATE "near_source_model_layer"."acct-06-30" SET "last_pay_post_date"=null WHERE "last_pay_post_date"=''; 
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_no Type varchar(50);
Alter Table "near_source_model_layer"."acct-06-30" Alter column org_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-06-30" Alter column cust_id Type varchar(50);
Alter Table "near_source_model_layer"."acct-06-30" Alter column application_no Type varchar(50);
Alter Table "near_source_model_layer"."acct-06-30" Alter column market_active_code Type varchar(50);
Alter Table "near_source_model_layer"."acct-06-30" Alter column open_acct_date Type date Using(open_acct_date::date);
Alter Table "near_source_model_layer"."acct-06-30" Alter column cancel_acct_date Type date Using(cancel_acct_date::date);
Alter Table "near_source_model_layer"."acct-06-30" Alter column invalid_date Type date Using(invalid_date::date);
Alter Table "near_source_model_layer"."acct-06-30" Alter column branch_code Type varchar(10);
Alter Table "near_source_model_layer"."acct-06-30" Alter column send_card_type_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-06-30" Alter column issue_channel_code Type varchar(4);
Alter Table "near_source_model_layer"."acct-06-30" Alter column reference_code Type varchar(5);
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_date Type char(2) Using(acct_date::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column card_count Type numeric Using(card_count::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column curr_balance Type numeric Using(curr_balance::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column curr_cash_balance Type numeric Using(curr_cash_balance::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column curr_retail_balance Type numeric Using(curr_retail_balance::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column curr_instalment_balance Type numeric Using(curr_instalment_balance::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column credit_amount Type numeric Using(credit_amount::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column debit_amount Type numeric Using(debit_amount::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column hand_fee_amt Type numeric Using(hand_fee_amt::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column late_fee_amt Type numeric Using(late_fee_amt::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column year_fee_amt Type numeric Using(year_fee_amt::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column over_limit_amt Type numeric Using(over_limit_amt::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column last_term_balance Type numeric Using(last_term_balance::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column payment_amount Type numeric Using(payment_amount::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column activity_status_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_status_code Type varchar(1);
Alter Table "near_source_model_layer"."acct-06-30" Alter column lock_stat_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-06-30" Alter column lock_off_date Type date Using(lock_off_date::date);
Alter Table "near_source_model_layer"."acct-06-30" Alter column year_fee Type numeric Using(year_fee::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column avoid_year_fee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-06-30" Alter column avoid_ratefee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-06-30" Alter column avoid_limit_fee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-06-30" Alter column avoid_late_fee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-06-30" Alter column avoid_transfer_fee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-06-30" Alter column avoid_domestic_atm_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-06-30" Alter column avoid_oversea_atm_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-06-30" Alter column share_cust_limit_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-06-30" Alter column override_cust_limit_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-06-30" Alter column auto_repay_type_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-06-30" Alter column credit_limit Type numeric Using(credit_limit::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column recent_limit_adj_date Type date Using(recent_limit_adj_date::date);
Alter Table "near_source_model_layer"."acct-06-30" Alter column curr_limit Type numeric Using(curr_limit::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column take_cash_limit Type numeric Using(take_cash_limit::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column net_charge_limit Type numeric Using(net_charge_limit::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column temp_credit_limit Type numeric Using(temp_credit_limit::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column temp_limit_adj_count Type numeric Using(temp_limit_adj_count::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column over_limit_count Type numeric Using(over_limit_count::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_count Type numeric Using(overdue_count::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_0_29_day_balance Type numeric Using(overdue_0_29_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_0_29_day_count Type numeric Using(overdue_0_29_day_count::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_30_59_day_balance Type numeric Using(overdue_30_59_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_30_59_day_count Type numeric Using(overdue_30_59_day_count::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_60_89_day_balance Type numeric Using(overdue_60_89_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_60_89_day_count Type numeric Using(overdue_60_89_day_count::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_90_119_day_balance Type numeric Using(overdue_90_119_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_90_119_day_count Type numeric Using(overdue_90_119_day_count::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_120_149_day_balance Type numeric Using(overdue_120_149_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_120_149_day_count Type numeric Using(overdue_120_149_day_count::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_150_179_day_balance Type numeric Using(overdue_150_179_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_150_179_day_count Type numeric Using(overdue_150_179_day_count::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_180_209_day_balance Type numeric Using(overdue_180_209_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_180_209_day_count Type numeric Using(overdue_180_209_day_count::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_up_210_day_balance Type numeric Using(overdue_up_210_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column overdue_up_210_day_count Type numeric Using(overdue_up_210_day_count::numeric);
Alter Table "near_source_model_layer"."acct-06-30" Alter column first_trans_post_date Type date Using(first_trans_post_date::date);
Alter Table "near_source_model_layer"."acct-06-30" Alter column last_cons_post_date Type date Using(last_cons_post_date::date);
Alter Table "near_source_model_layer"."acct-06-30" Alter column last_cash_post_date Type date Using(last_cash_post_date::date);
Alter Table "near_source_model_layer"."acct-06-30" Alter column last_pay_post_date Type date Using(last_pay_post_date::date);
Alter Table "near_source_model_layer"."acct-06-30" Alter column last_balan_chg_date Type date Using(last_balan_chg_date::date);
Alter Table "near_source_model_layer"."acct-06-30" Alter column last_overdue_date Type date Using(last_overdue_date::date);
Alter Table "near_source_model_layer"."acct-06-30" Alter column transfer_date Type date Using(transfer_date::date);
Alter Table "near_source_model_layer"."acct-06-30" Alter column transfer_acct_no Type varchar(50);
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_1 Type char(2) Using(acct_status_1::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_2 Type char(2) Using(acct_status_2::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_3 Type char(2) Using(acct_status_3::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_4 Type char(2) Using(acct_status_4::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_5 Type char(2) Using(acct_status_5::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_6 Type char(2) Using(acct_status_6::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_7 Type char(2) Using(acct_status_7::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_8 Type char(2) Using(acct_status_8::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_9 Type char(2) Using(acct_status_9::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_10 Type char(2) Using(acct_status_10::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_11 Type char(2) Using(acct_status_11::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_12 Type char(2) Using(acct_status_12::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_13 Type char(2) Using(acct_status_13::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_14 Type char(2) Using(acct_status_14::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_15 Type char(2) Using(acct_status_15::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_16 Type char(2) Using(acct_status_16::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_17 Type char(2) Using(acct_status_17::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_18 Type char(2) Using(acct_status_18::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_19 Type char(2) Using(acct_status_19::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_20 Type char(2) Using(acct_status_20::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_21 Type char(2) Using(acct_status_21::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_22 Type char(2) Using(acct_status_22::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_23 Type char(2) Using(acct_status_23::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_status_24 Type char(2) Using(acct_status_24::char(2));
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_3_mm_overdue_value Type varchar;
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_6_mm_overdue_value Type varchar;
Alter Table "near_source_model_layer"."acct-06-30" Alter column acct_check_cycle Type varchar;
UPDATE "near_source_model_layer"."acct-07-31" SET "last_cons_post_date"=null WHERE "last_cons_post_date"=''; 
UPDATE "near_source_model_layer"."acct-07-31" SET "last_cash_post_date"=null WHERE "last_cash_post_date"=''; 
UPDATE "near_source_model_layer"."acct-07-31" SET "last_pay_post_date"=null WHERE "last_pay_post_date"=''; 
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_no Type varchar(50);
Alter Table "near_source_model_layer"."acct-07-31" Alter column org_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-07-31" Alter column cust_id Type varchar(50);
Alter Table "near_source_model_layer"."acct-07-31" Alter column application_no Type varchar(50);
Alter Table "near_source_model_layer"."acct-07-31" Alter column market_active_code Type varchar(50);
Alter Table "near_source_model_layer"."acct-07-31" Alter column open_acct_date Type date Using(open_acct_date::date);
Alter Table "near_source_model_layer"."acct-07-31" Alter column cancel_acct_date Type date Using(cancel_acct_date::date);
Alter Table "near_source_model_layer"."acct-07-31" Alter column invalid_date Type date Using(invalid_date::date);
Alter Table "near_source_model_layer"."acct-07-31" Alter column branch_code Type varchar(10);
Alter Table "near_source_model_layer"."acct-07-31" Alter column send_card_type_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-07-31" Alter column issue_channel_code Type varchar(4);
Alter Table "near_source_model_layer"."acct-07-31" Alter column reference_code Type varchar(5);
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_date Type char(2) Using(acct_date::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column card_count Type numeric Using(card_count::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column curr_balance Type numeric Using(curr_balance::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column curr_cash_balance Type numeric Using(curr_cash_balance::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column curr_retail_balance Type numeric Using(curr_retail_balance::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column curr_instalment_balance Type numeric Using(curr_instalment_balance::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column credit_amount Type numeric Using(credit_amount::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column debit_amount Type numeric Using(debit_amount::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column hand_fee_amt Type numeric Using(hand_fee_amt::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column late_fee_amt Type numeric Using(late_fee_amt::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column year_fee_amt Type numeric Using(year_fee_amt::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column over_limit_amt Type numeric Using(over_limit_amt::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column last_term_balance Type numeric Using(last_term_balance::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column payment_amount Type numeric Using(payment_amount::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column activity_status_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_status_code Type varchar(1);
Alter Table "near_source_model_layer"."acct-07-31" Alter column lock_stat_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-07-31" Alter column lock_off_date Type date Using(lock_off_date::date);
Alter Table "near_source_model_layer"."acct-07-31" Alter column year_fee Type numeric Using(year_fee::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column avoid_year_fee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-07-31" Alter column avoid_ratefee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-07-31" Alter column avoid_limit_fee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-07-31" Alter column avoid_late_fee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-07-31" Alter column avoid_transfer_fee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-07-31" Alter column avoid_domestic_atm_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-07-31" Alter column avoid_oversea_atm_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-07-31" Alter column share_cust_limit_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-07-31" Alter column override_cust_limit_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-07-31" Alter column auto_repay_type_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-07-31" Alter column credit_limit Type numeric Using(credit_limit::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column recent_limit_adj_date Type date Using(recent_limit_adj_date::date);
Alter Table "near_source_model_layer"."acct-07-31" Alter column curr_limit Type numeric Using(curr_limit::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column take_cash_limit Type numeric Using(take_cash_limit::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column net_charge_limit Type numeric Using(net_charge_limit::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column temp_credit_limit Type numeric Using(temp_credit_limit::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column temp_limit_adj_count Type numeric Using(temp_limit_adj_count::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column over_limit_count Type numeric Using(over_limit_count::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_count Type numeric Using(overdue_count::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_0_29_day_balance Type numeric Using(overdue_0_29_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_0_29_day_count Type numeric Using(overdue_0_29_day_count::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_30_59_day_balance Type numeric Using(overdue_30_59_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_30_59_day_count Type numeric Using(overdue_30_59_day_count::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_60_89_day_balance Type numeric Using(overdue_60_89_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_60_89_day_count Type numeric Using(overdue_60_89_day_count::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_90_119_day_balance Type numeric Using(overdue_90_119_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_90_119_day_count Type numeric Using(overdue_90_119_day_count::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_120_149_day_balance Type numeric Using(overdue_120_149_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_120_149_day_count Type numeric Using(overdue_120_149_day_count::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_150_179_day_balance Type numeric Using(overdue_150_179_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_150_179_day_count Type numeric Using(overdue_150_179_day_count::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_180_209_day_balance Type numeric Using(overdue_180_209_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_180_209_day_count Type numeric Using(overdue_180_209_day_count::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_up_210_day_balance Type numeric Using(overdue_up_210_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column overdue_up_210_day_count Type numeric Using(overdue_up_210_day_count::numeric);
Alter Table "near_source_model_layer"."acct-07-31" Alter column first_trans_post_date Type date Using(first_trans_post_date::date);
Alter Table "near_source_model_layer"."acct-07-31" Alter column last_cons_post_date Type date Using(last_cons_post_date::date);
Alter Table "near_source_model_layer"."acct-07-31" Alter column last_cash_post_date Type date Using(last_cash_post_date::date);
Alter Table "near_source_model_layer"."acct-07-31" Alter column last_pay_post_date Type date Using(last_pay_post_date::date);
Alter Table "near_source_model_layer"."acct-07-31" Alter column last_balan_chg_date Type date Using(last_balan_chg_date::date);
Alter Table "near_source_model_layer"."acct-07-31" Alter column last_overdue_date Type date Using(last_overdue_date::date);
Alter Table "near_source_model_layer"."acct-07-31" Alter column transfer_date Type date Using(transfer_date::date);
Alter Table "near_source_model_layer"."acct-07-31" Alter column transfer_acct_no Type varchar(50);
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_1 Type char(2) Using(acct_status_1::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_2 Type char(2) Using(acct_status_2::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_3 Type char(2) Using(acct_status_3::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_4 Type char(2) Using(acct_status_4::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_5 Type char(2) Using(acct_status_5::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_6 Type char(2) Using(acct_status_6::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_7 Type char(2) Using(acct_status_7::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_8 Type char(2) Using(acct_status_8::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_9 Type char(2) Using(acct_status_9::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_10 Type char(2) Using(acct_status_10::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_11 Type char(2) Using(acct_status_11::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_12 Type char(2) Using(acct_status_12::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_13 Type char(2) Using(acct_status_13::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_14 Type char(2) Using(acct_status_14::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_15 Type char(2) Using(acct_status_15::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_16 Type char(2) Using(acct_status_16::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_17 Type char(2) Using(acct_status_17::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_18 Type char(2) Using(acct_status_18::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_19 Type char(2) Using(acct_status_19::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_20 Type char(2) Using(acct_status_20::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_21 Type char(2) Using(acct_status_21::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_22 Type char(2) Using(acct_status_22::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_23 Type char(2) Using(acct_status_23::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_status_24 Type char(2) Using(acct_status_24::char(2));
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_3_mm_overdue_value Type varchar;
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_6_mm_overdue_value Type varchar;
Alter Table "near_source_model_layer"."acct-07-31" Alter column acct_check_cycle Type varchar;

UPDATE "near_source_model_layer"."acct-08-31" SET "last_cons_post_date"=null WHERE "last_cons_post_date"=''; 
UPDATE "near_source_model_layer"."acct-08-31" SET "last_cash_post_date"=null WHERE "last_cash_post_date"=''; 
UPDATE "near_source_model_layer"."acct-08-31" SET "last_pay_post_date"=null WHERE "last_pay_post_date"=''; 
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_no Type varchar(50);
Alter Table "near_source_model_layer"."acct-08-31" Alter column org_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-08-31" Alter column cust_id Type varchar(50);
Alter Table "near_source_model_layer"."acct-08-31" Alter column application_no Type varchar(50);
Alter Table "near_source_model_layer"."acct-08-31" Alter column market_active_code Type varchar(50);
Alter Table "near_source_model_layer"."acct-08-31" Alter column open_acct_date Type date Using(open_acct_date::date);
Alter Table "near_source_model_layer"."acct-08-31" Alter column cancel_acct_date Type date Using(cancel_acct_date::date);
Alter Table "near_source_model_layer"."acct-08-31" Alter column invalid_date Type date Using(invalid_date::date);
Alter Table "near_source_model_layer"."acct-08-31" Alter column branch_code Type varchar(10);
Alter Table "near_source_model_layer"."acct-08-31" Alter column send_card_type_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-08-31" Alter column issue_channel_code Type varchar(4);
Alter Table "near_source_model_layer"."acct-08-31" Alter column reference_code Type varchar(5);
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_date Type char(2) Using(acct_date::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column card_count Type numeric Using(card_count::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column curr_balance Type numeric Using(curr_balance::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column curr_cash_balance Type numeric Using(curr_cash_balance::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column curr_retail_balance Type numeric Using(curr_retail_balance::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column curr_instalment_balance Type numeric Using(curr_instalment_balance::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column credit_amount Type numeric Using(credit_amount::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column debit_amount Type numeric Using(debit_amount::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column hand_fee_amt Type numeric Using(hand_fee_amt::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column late_fee_amt Type numeric Using(late_fee_amt::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column year_fee_amt Type numeric Using(year_fee_amt::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column over_limit_amt Type numeric Using(over_limit_amt::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column last_term_balance Type numeric Using(last_term_balance::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column payment_amount Type numeric Using(payment_amount::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column activity_status_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_status_code Type varchar(1);
Alter Table "near_source_model_layer"."acct-08-31" Alter column lock_stat_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-08-31" Alter column lock_off_date Type date Using(lock_off_date::date);
Alter Table "near_source_model_layer"."acct-08-31" Alter column year_fee Type numeric Using(year_fee::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column avoid_year_fee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-08-31" Alter column avoid_ratefee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-08-31" Alter column avoid_limit_fee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-08-31" Alter column avoid_late_fee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-08-31" Alter column avoid_transfer_fee_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-08-31" Alter column avoid_domestic_atm_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-08-31" Alter column avoid_oversea_atm_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-08-31" Alter column share_cust_limit_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-08-31" Alter column override_cust_limit_flag Type varchar(1);
Alter Table "near_source_model_layer"."acct-08-31" Alter column auto_repay_type_code Type varchar(3);
Alter Table "near_source_model_layer"."acct-08-31" Alter column credit_limit Type numeric Using(credit_limit::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column recent_limit_adj_date Type date Using(recent_limit_adj_date::date);
Alter Table "near_source_model_layer"."acct-08-31" Alter column curr_limit Type numeric Using(curr_limit::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column take_cash_limit Type numeric Using(take_cash_limit::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column net_charge_limit Type numeric Using(net_charge_limit::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column temp_credit_limit Type numeric Using(temp_credit_limit::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column temp_limit_adj_count Type numeric Using(temp_limit_adj_count::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column over_limit_count Type numeric Using(over_limit_count::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_count Type numeric Using(overdue_count::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_0_29_day_balance Type numeric Using(overdue_0_29_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_0_29_day_count Type numeric Using(overdue_0_29_day_count::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_30_59_day_balance Type numeric Using(overdue_30_59_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_30_59_day_count Type numeric Using(overdue_30_59_day_count::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_60_89_day_balance Type numeric Using(overdue_60_89_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_60_89_day_count Type numeric Using(overdue_60_89_day_count::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_90_119_day_balance Type numeric Using(overdue_90_119_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_90_119_day_count Type numeric Using(overdue_90_119_day_count::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_120_149_day_balance Type numeric Using(overdue_120_149_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_120_149_day_count Type numeric Using(overdue_120_149_day_count::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_150_179_day_balance Type numeric Using(overdue_150_179_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_150_179_day_count Type numeric Using(overdue_150_179_day_count::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_180_209_day_balance Type numeric Using(overdue_180_209_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_180_209_day_count Type numeric Using(overdue_180_209_day_count::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_up_210_day_balance Type numeric Using(overdue_up_210_day_balance::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column overdue_up_210_day_count Type numeric Using(overdue_up_210_day_count::numeric);
Alter Table "near_source_model_layer"."acct-08-31" Alter column first_trans_post_date Type date Using(first_trans_post_date::date);
Alter Table "near_source_model_layer"."acct-08-31" Alter column last_cons_post_date Type date Using(last_cons_post_date::date);
Alter Table "near_source_model_layer"."acct-08-31" Alter column last_cash_post_date Type date Using(last_cash_post_date::date);
Alter Table "near_source_model_layer"."acct-08-31" Alter column last_pay_post_date Type date Using(last_pay_post_date::date);
Alter Table "near_source_model_layer"."acct-08-31" Alter column last_balan_chg_date Type date Using(last_balan_chg_date::date);
Alter Table "near_source_model_layer"."acct-08-31" Alter column last_overdue_date Type date Using(last_overdue_date::date);
Alter Table "near_source_model_layer"."acct-08-31" Alter column transfer_date Type date Using(transfer_date::date);
Alter Table "near_source_model_layer"."acct-08-31" Alter column transfer_acct_no Type varchar(50);
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_1 Type char(2) Using(acct_status_1::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_2 Type char(2) Using(acct_status_2::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_3 Type char(2) Using(acct_status_3::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_4 Type char(2) Using(acct_status_4::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_5 Type char(2) Using(acct_status_5::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_6 Type char(2) Using(acct_status_6::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_7 Type char(2) Using(acct_status_7::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_8 Type char(2) Using(acct_status_8::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_9 Type char(2) Using(acct_status_9::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_10 Type char(2) Using(acct_status_10::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_11 Type char(2) Using(acct_status_11::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_12 Type char(2) Using(acct_status_12::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_13 Type char(2) Using(acct_status_13::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_14 Type char(2) Using(acct_status_14::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_15 Type char(2) Using(acct_status_15::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_16 Type char(2) Using(acct_status_16::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_17 Type char(2) Using(acct_status_17::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_18 Type char(2) Using(acct_status_18::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_19 Type char(2) Using(acct_status_19::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_20 Type char(2) Using(acct_status_20::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_21 Type char(2) Using(acct_status_21::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_22 Type char(2) Using(acct_status_22::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_23 Type char(2) Using(acct_status_23::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_status_24 Type char(2) Using(acct_status_24::char(2));
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_3_mm_overdue_value Type varchar;
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_6_mm_overdue_value Type varchar;
Alter Table "near_source_model_layer"."acct-08-31" Alter column acct_check_cycle Type varchar;
Alter Table "near_source_model_layer"."card-06-30" Alter column "card_no" Type varchar(50) Using("card_no"::varchar(50));
Alter Table "near_source_model_layer"."card-06-30" Alter column "acct_no" Type varchar(50) Using("acct_no"::varchar(50));
Alter Table "near_source_model_layer"."card-06-30" Alter column "cust_id" Type varchar(50) Using("cust_id"::varchar(50));
Alter Table "near_source_model_layer"."card-06-30" Alter column "master_card_no" Type varchar(50) Using("master_card_no"::varchar(50));
Alter Table "near_source_model_layer"."card-06-30" Alter column "branch_code" Type varchar(10) Using("branch_code"::varchar(10));
Alter Table "near_source_model_layer"."card-06-30" Alter column "issue_channel_code" Type varchar(4) Using("issue_channel_code"::varchar(4));
Alter Table "near_source_model_layer"."card-06-30" Alter column "reference_code" Type varchar(5) Using("reference_code"::varchar(5));
Alter Table "near_source_model_layer"."card-06-30" Alter column "bin_code" Type varchar(6) Using("bin_code"::varchar(6));
Alter Table "near_source_model_layer"."card-06-30" Alter column "logo_code" Type varchar(3) Using("logo_code"::varchar(3));
Alter Table "near_source_model_layer"."card-06-30" Alter column "ent_logo_code" Type varchar(4) Using("ent_logo_code"::varchar(4));
Alter Table "near_source_model_layer"."card-06-30" Alter column "card_kind_code" Type varchar(2) Using("card_kind_code"::varchar(2));
Alter Table "near_source_model_layer"."card-06-30" Alter column "card_status_code" Type varchar(3) Using("card_status_code"::varchar(3));
Alter Table "near_source_model_layer"."card-06-30" Alter column "lock_stat_code" Type varchar(3) Using("lock_stat_code"::varchar(3));
Alter Table "near_source_model_layer"."card-06-30" Alter column "lock_off_date" Type date Using("lock_off_date"::date);
Alter Table "near_source_model_layer"."card-06-30" Alter column "card_issue_date" Type date Using("card_issue_date"::date);
Alter Table "near_source_model_layer"."card-06-30" Alter column "maturity_date" Type date Using("maturity_date"::date);
Alter Table "near_source_model_layer"."card-06-30" Alter column "open_card_date" Type date Using("open_card_date"::date);
Alter Table "near_source_model_layer"."card-06-30" Alter column "cancel_card_date" Type date Using("cancel_card_date"::date);
Alter Table "near_source_model_layer"."card-06-30" Alter column "invalid_date" Type date Using("invalid_date"::date);
Alter Table "near_source_model_layer"."card-06-30" Alter column "active_date" Type date Using("active_date"::date);
Alter Table "near_source_model_layer"."card-06-30" Alter column "first_use_date" Type date Using("first_use_date"::date);
Alter Table "near_source_model_layer"."card-06-30" Alter column "last_consume_date" Type date Using("last_consume_date"::date);
Alter Table "near_source_model_layer"."card-06-30" Alter column "last_take_cash_date" Type date Using("last_take_cash_date"::date);
Alter Table "near_source_model_layer"."card-06-30" Alter column "last_payment_date" Type date Using("last_payment_date"::date);
Alter Table "near_source_model_layer"."card-06-30" Alter column "primary_flag" Type varchar(1) Using("primary_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-06-30" Alter column "public_private_code" Type varchar(3) Using("public_private_code"::varchar(3));
Alter Table "near_source_model_layer"."card-06-30" Alter column "employee_flag" Type varchar(1) Using("employee_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-06-30" Alter column "activity_status_code" Type varchar(3) Using("activity_status_code"::varchar(3));
Alter Table "near_source_model_layer"."card-06-30" Alter column "auto_installment_flag" Type varchar(1) Using("auto_installment_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-06-30" Alter column "picture_card_flag" Type varchar(1) Using("picture_card_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-06-30" Alter column "avoid_year_fee_flag" Type varchar(1) Using("avoid_year_fee_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-06-30" Alter column "pay_condition_code" Type varchar(1) Using("pay_condition_code"::varchar(1));
Alter Table "near_source_model_layer"."card-06-30" Alter column "year_fee" Type numeric Using("year_fee"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "next_charge_date" Type date Using("next_charge_date"::date);
Alter Table "near_source_model_layer"."card-06-30" Alter column "rmb_cyc_auth_limit" Type numeric Using("rmb_cyc_auth_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "usd_cyc_auth_limit" Type numeric Using("usd_cyc_auth_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "rmb_cyc_atm_limit" Type numeric Using("rmb_cyc_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "usd_cyc_atm_limit" Type numeric Using("usd_cyc_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "rmb_day_atm_limi" Type numeric Using("rmb_day_atm_limi"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "usd_day_atm_limit" Type numeric Using("usd_day_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "rmb_times_atm_limit" Type numeric Using("rmb_times_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "usd_times_atm_limit" Type numeric Using("usd_times_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "rmb_cyc_otc_limit" Type numeric Using("rmb_cyc_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "usd_cyc_otc_limit" Type numeric Using("usd_cyc_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "rmb_day_otc_limit" Type numeric Using("rmb_day_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "usd_day_otc_limit" Type numeric Using("usd_day_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "rmb_times_otc_limit" Type numeric Using("rmb_times_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "usd_times_otc_limit" Type numeric Using("usd_times_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "rmb_cyc_pos_limit" Type numeric Using("rmb_cyc_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "usd_cyc_pos_limit" Type numeric Using("usd_cyc_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "rmb_day_pos_limit" Type numeric Using("rmb_day_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "usd_day_pos_limit" Type numeric Using("usd_day_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "rmb_times_pos_limit" Type numeric Using("rmb_times_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "usd_times_pos_limit" Type numeric Using("usd_times_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "rmb_cyc_net_limit" Type numeric Using("rmb_cyc_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "usd_cyc_net_limit" Type numeric Using("usd_cyc_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "rmb_day_net_limit" Type numeric Using("rmb_day_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "usd_day_net_limit" Type numeric Using("usd_day_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "rmb_times_net_limit" Type numeric Using("rmb_times_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "usd_times_net_limit" Type numeric Using("usd_times_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-06-30" Alter column "card_lev_flag" Type varchar(3) Using("card_lev_flag"::varchar(3));
Alter Table "near_source_model_layer"."card-06-30" Alter column "card_mark_flag" Type varchar(3) Using("card_mark_flag"::varchar(3));
Alter Table "near_source_model_layer"."card-06-30" Alter column "product_type_flag" Type varchar(4) Using("product_type_flag"::varchar(4));
Alter Table "near_source_model_layer"."card-07-31" Alter column "card_no" Type varchar(50) Using("card_no"::varchar(50));
Alter Table "near_source_model_layer"."card-07-31" Alter column "acct_no" Type varchar(50) Using("acct_no"::varchar(50));
Alter Table "near_source_model_layer"."card-07-31" Alter column "cust_id" Type varchar(50) Using("cust_id"::varchar(50));
Alter Table "near_source_model_layer"."card-07-31" Alter column "master_card_no" Type varchar(50) Using("master_card_no"::varchar(50));
Alter Table "near_source_model_layer"."card-07-31" Alter column "branch_code" Type varchar(10) Using("branch_code"::varchar(10));
Alter Table "near_source_model_layer"."card-07-31" Alter column "issue_channel_code" Type varchar(4) Using("issue_channel_code"::varchar(4));
Alter Table "near_source_model_layer"."card-07-31" Alter column "reference_code" Type varchar(5) Using("reference_code"::varchar(5));
Alter Table "near_source_model_layer"."card-07-31" Alter column "bin_code" Type varchar(6) Using("bin_code"::varchar(6));
Alter Table "near_source_model_layer"."card-07-31" Alter column "logo_code" Type varchar(3) Using("logo_code"::varchar(3));
Alter Table "near_source_model_layer"."card-07-31" Alter column "ent_logo_code" Type varchar(4) Using("ent_logo_code"::varchar(4));
Alter Table "near_source_model_layer"."card-07-31" Alter column "card_kind_code" Type varchar(2) Using("card_kind_code"::varchar(2));
Alter Table "near_source_model_layer"."card-07-31" Alter column "card_status_code" Type varchar(3) Using("card_status_code"::varchar(3));
Alter Table "near_source_model_layer"."card-07-31" Alter column "lock_stat_code" Type varchar(3) Using("lock_stat_code"::varchar(3));
Alter Table "near_source_model_layer"."card-07-31" Alter column "lock_off_date" Type date Using("lock_off_date"::date);
Alter Table "near_source_model_layer"."card-07-31" Alter column "card_issue_date" Type date Using("card_issue_date"::date);
Alter Table "near_source_model_layer"."card-07-31" Alter column "maturity_date" Type date Using("maturity_date"::date);
Alter Table "near_source_model_layer"."card-07-31" Alter column "open_card_date" Type date Using("open_card_date"::date);
Alter Table "near_source_model_layer"."card-07-31" Alter column "cancel_card_date" Type date Using("cancel_card_date"::date);
Alter Table "near_source_model_layer"."card-07-31" Alter column "invalid_date" Type date Using("invalid_date"::date);
Alter Table "near_source_model_layer"."card-07-31" Alter column "active_date" Type date Using("active_date"::date);
Alter Table "near_source_model_layer"."card-07-31" Alter column "first_use_date" Type date Using("first_use_date"::date);
Alter Table "near_source_model_layer"."card-07-31" Alter column "last_consume_date" Type date Using("last_consume_date"::date);
Alter Table "near_source_model_layer"."card-07-31" Alter column "last_take_cash_date" Type date Using("last_take_cash_date"::date);
Alter Table "near_source_model_layer"."card-07-31" Alter column "last_payment_date" Type date Using("last_payment_date"::date);
Alter Table "near_source_model_layer"."card-07-31" Alter column "primary_flag" Type varchar(1) Using("primary_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-07-31" Alter column "public_private_code" Type varchar(3) Using("public_private_code"::varchar(3));
Alter Table "near_source_model_layer"."card-07-31" Alter column "employee_flag" Type varchar(1) Using("employee_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-07-31" Alter column "activity_status_code" Type varchar(3) Using("activity_status_code"::varchar(3));
Alter Table "near_source_model_layer"."card-07-31" Alter column "auto_installment_flag" Type varchar(1) Using("auto_installment_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-07-31" Alter column "picture_card_flag" Type varchar(1) Using("picture_card_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-07-31" Alter column "avoid_year_fee_flag" Type varchar(1) Using("avoid_year_fee_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-07-31" Alter column "pay_condition_code" Type varchar(1) Using("pay_condition_code"::varchar(1));
Alter Table "near_source_model_layer"."card-07-31" Alter column "year_fee" Type numeric Using("year_fee"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "next_charge_date" Type date Using("next_charge_date"::date);
Alter Table "near_source_model_layer"."card-07-31" Alter column "rmb_cyc_auth_limit" Type numeric Using("rmb_cyc_auth_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "usd_cyc_auth_limit" Type numeric Using("usd_cyc_auth_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "rmb_cyc_atm_limit" Type numeric Using("rmb_cyc_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "usd_cyc_atm_limit" Type numeric Using("usd_cyc_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "rmb_day_atm_limi" Type numeric Using("rmb_day_atm_limi"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "usd_day_atm_limit" Type numeric Using("usd_day_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "rmb_times_atm_limit" Type numeric Using("rmb_times_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "usd_times_atm_limit" Type numeric Using("usd_times_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "rmb_cyc_otc_limit" Type numeric Using("rmb_cyc_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "usd_cyc_otc_limit" Type numeric Using("usd_cyc_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "rmb_day_otc_limit" Type numeric Using("rmb_day_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "usd_day_otc_limit" Type numeric Using("usd_day_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "rmb_times_otc_limit" Type numeric Using("rmb_times_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "usd_times_otc_limit" Type numeric Using("usd_times_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "rmb_cyc_pos_limit" Type numeric Using("rmb_cyc_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "usd_cyc_pos_limit" Type numeric Using("usd_cyc_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "rmb_day_pos_limit" Type numeric Using("rmb_day_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "usd_day_pos_limit" Type numeric Using("usd_day_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "rmb_times_pos_limit" Type numeric Using("rmb_times_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "usd_times_pos_limit" Type numeric Using("usd_times_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "rmb_cyc_net_limit" Type numeric Using("rmb_cyc_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "usd_cyc_net_limit" Type numeric Using("usd_cyc_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "rmb_day_net_limit" Type numeric Using("rmb_day_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "usd_day_net_limit" Type numeric Using("usd_day_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "rmb_times_net_limit" Type numeric Using("rmb_times_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "usd_times_net_limit" Type numeric Using("usd_times_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-07-31" Alter column "card_lev_flag" Type varchar(3) Using("card_lev_flag"::varchar(3));
Alter Table "near_source_model_layer"."card-07-31" Alter column "card_mark_flag" Type varchar(3) Using("card_mark_flag"::varchar(3));
Alter Table "near_source_model_layer"."card-07-31" Alter column "product_type_flag" Type varchar(4) Using("product_type_flag"::varchar(4));
Alter Table "near_source_model_layer"."card-08-31" Alter column "card_no" Type varchar(50) Using("card_no"::varchar(50));
Alter Table "near_source_model_layer"."card-08-31" Alter column "acct_no" Type varchar(50) Using("acct_no"::varchar(50));
Alter Table "near_source_model_layer"."card-08-31" Alter column "cust_id" Type varchar(50) Using("cust_id"::varchar(50));
Alter Table "near_source_model_layer"."card-08-31" Alter column "master_card_no" Type varchar(50) Using("master_card_no"::varchar(50));
Alter Table "near_source_model_layer"."card-08-31" Alter column "branch_code" Type varchar(10) Using("branch_code"::varchar(10));
Alter Table "near_source_model_layer"."card-08-31" Alter column "issue_channel_code" Type varchar(4) Using("issue_channel_code"::varchar(4));
Alter Table "near_source_model_layer"."card-08-31" Alter column "reference_code" Type varchar(5) Using("reference_code"::varchar(5));
Alter Table "near_source_model_layer"."card-08-31" Alter column "bin_code" Type varchar(6) Using("bin_code"::varchar(6));
Alter Table "near_source_model_layer"."card-08-31" Alter column "logo_code" Type varchar(3) Using("logo_code"::varchar(3));
Alter Table "near_source_model_layer"."card-08-31" Alter column "ent_logo_code" Type varchar(4) Using("ent_logo_code"::varchar(4));
Alter Table "near_source_model_layer"."card-08-31" Alter column "card_kind_code" Type varchar(2) Using("card_kind_code"::varchar(2));
Alter Table "near_source_model_layer"."card-08-31" Alter column "card_status_code" Type varchar(3) Using("card_status_code"::varchar(3));
Alter Table "near_source_model_layer"."card-08-31" Alter column "lock_stat_code" Type varchar(3) Using("lock_stat_code"::varchar(3));
Alter Table "near_source_model_layer"."card-08-31" Alter column "lock_off_date" Type date Using("lock_off_date"::date);
Alter Table "near_source_model_layer"."card-08-31" Alter column "card_issue_date" Type date Using("card_issue_date"::date);
Alter Table "near_source_model_layer"."card-08-31" Alter column "maturity_date" Type date Using("maturity_date"::date);
Alter Table "near_source_model_layer"."card-08-31" Alter column "open_card_date" Type date Using("open_card_date"::date);
Alter Table "near_source_model_layer"."card-08-31" Alter column "cancel_card_date" Type date Using("cancel_card_date"::date);
Alter Table "near_source_model_layer"."card-08-31" Alter column "invalid_date" Type date Using("invalid_date"::date);
Alter Table "near_source_model_layer"."card-08-31" Alter column "active_date" Type date Using("active_date"::date);
Alter Table "near_source_model_layer"."card-08-31" Alter column "first_use_date" Type date Using("first_use_date"::date);
Alter Table "near_source_model_layer"."card-08-31" Alter column "last_consume_date" Type date Using("last_consume_date"::date);
Alter Table "near_source_model_layer"."card-08-31" Alter column "last_take_cash_date" Type date Using("last_take_cash_date"::date);
Alter Table "near_source_model_layer"."card-08-31" Alter column "last_payment_date" Type date Using("last_payment_date"::date);
Alter Table "near_source_model_layer"."card-08-31" Alter column "primary_flag" Type varchar(1) Using("primary_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-08-31" Alter column "public_private_code" Type varchar(3) Using("public_private_code"::varchar(3));
Alter Table "near_source_model_layer"."card-08-31" Alter column "employee_flag" Type varchar(1) Using("employee_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-08-31" Alter column "activity_status_code" Type varchar(3) Using("activity_status_code"::varchar(3));
Alter Table "near_source_model_layer"."card-08-31" Alter column "auto_installment_flag" Type varchar(1) Using("auto_installment_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-08-31" Alter column "picture_card_flag" Type varchar(1) Using("picture_card_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-08-31" Alter column "avoid_year_fee_flag" Type varchar(1) Using("avoid_year_fee_flag"::varchar(1));
Alter Table "near_source_model_layer"."card-08-31" Alter column "pay_condition_code" Type varchar(1) Using("pay_condition_code"::varchar(1));
Alter Table "near_source_model_layer"."card-08-31" Alter column "year_fee" Type numeric Using("year_fee"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "next_charge_date" Type date Using("next_charge_date"::date);
Alter Table "near_source_model_layer"."card-08-31" Alter column "rmb_cyc_auth_limit" Type numeric Using("rmb_cyc_auth_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "usd_cyc_auth_limit" Type numeric Using("usd_cyc_auth_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "rmb_cyc_atm_limit" Type numeric Using("rmb_cyc_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "usd_cyc_atm_limit" Type numeric Using("usd_cyc_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "rmb_day_atm_limi" Type numeric Using("rmb_day_atm_limi"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "usd_day_atm_limit" Type numeric Using("usd_day_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "rmb_times_atm_limit" Type numeric Using("rmb_times_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "usd_times_atm_limit" Type numeric Using("usd_times_atm_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "rmb_cyc_otc_limit" Type numeric Using("rmb_cyc_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "usd_cyc_otc_limit" Type numeric Using("usd_cyc_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "rmb_day_otc_limit" Type numeric Using("rmb_day_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "usd_day_otc_limit" Type numeric Using("usd_day_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "rmb_times_otc_limit" Type numeric Using("rmb_times_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "usd_times_otc_limit" Type numeric Using("usd_times_otc_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "rmb_cyc_pos_limit" Type numeric Using("rmb_cyc_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "usd_cyc_pos_limit" Type numeric Using("usd_cyc_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "rmb_day_pos_limit" Type numeric Using("rmb_day_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "usd_day_pos_limit" Type numeric Using("usd_day_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "rmb_times_pos_limit" Type numeric Using("rmb_times_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "usd_times_pos_limit" Type numeric Using("usd_times_pos_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "rmb_cyc_net_limit" Type numeric Using("rmb_cyc_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "usd_cyc_net_limit" Type numeric Using("usd_cyc_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "rmb_day_net_limit" Type numeric Using("rmb_day_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "usd_day_net_limit" Type numeric Using("usd_day_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "rmb_times_net_limit" Type numeric Using("rmb_times_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "usd_times_net_limit" Type numeric Using("usd_times_net_limit"::numeric);
Alter Table "near_source_model_layer"."card-08-31" Alter column "card_lev_flag" Type varchar(3) Using("card_lev_flag"::varchar(3));
Alter Table "near_source_model_layer"."card-08-31" Alter column "card_mark_flag" Type varchar(3) Using("card_mark_flag"::varchar(3));
Alter Table "near_source_model_layer"."card-08-31" Alter column "product_type_flag" Type varchar(4) Using("product_type_flag"::varchar(4));
Alter Table "near_source_model_layer"."cust-06-30" Alter column cust_id Type varchar(50) Using(cust_id::varchar(50));
Alter Table "near_source_model_layer"."cust-06-30" Alter column cust_name Type varchar(100) Using(cust_name::varchar(100));
Alter Table "near_source_model_layer"."cust-06-30" Alter column gender_code Type varchar(2) Using(gender_code::varchar(2));
Alter Table "near_source_model_layer"."cust-06-30" Alter column birthday Type date Using(birthday::date);
Alter Table "near_source_model_layer"."cust-06-30" Alter column age Type numeric Using(age::numeric);
Alter Table "near_source_model_layer"."cust-06-30" Alter column cert_type_code Type varchar(10) Using(cert_type_code::varchar(10));
Alter Table "near_source_model_layer"."cust-06-30" Alter column cert_no Type varchar(50) Using(cert_no::varchar(50));
Alter Table "near_source_model_layer"."cust-06-30" Alter column education_grade_code Type varchar(2) Using(education_grade_code::varchar(2));
Alter Table "near_source_model_layer"."cust-06-30" Alter column nation_code Type varchar(5) Using(nation_code::varchar(5));
Alter Table "near_source_model_layer"."cust-06-30" Alter column year_income Type numeric Using(year_income::numeric);
Alter Table "near_source_model_layer"."cust-06-30" Alter column marriage_status_code Type varchar(2) Using(marriage_status_code::varchar(2));
Alter Table "near_source_model_layer"."cust-06-30" Alter column house_kind_code Type varchar(2) Using(house_kind_code::varchar(2));
Alter Table "near_source_model_layer"."cust-06-30" Alter column reside_years Type numeric Using(reside_years::numeric);
Alter Table "near_source_model_layer"."cust-06-30" Alter column home_phone Type varchar(50) Using(home_phone::varchar(50));
Alter Table "near_source_model_layer"."cust-06-30" Alter column mobile_phone Type varchar(50) Using(mobile_phone::varchar(50));
Alter Table "near_source_model_layer"."cust-06-30" Alter column corp_phone Type varchar(50) Using(corp_phone::varchar(50));
Alter Table "near_source_model_layer"."cust-06-30" Alter column home_post_code Type varchar(10) Using(home_post_code::varchar(10));
Alter Table "near_source_model_layer"."cust-06-30" Alter column house_address Type varchar(200) Using(house_address::varchar(200));
Alter Table "near_source_model_layer"."cust-06-30" Alter column stmt_post_code Type varchar(10) Using(stmt_post_code::varchar(10));
Alter Table "near_source_model_layer"."cust-06-30" Alter column stmt_address Type varchar(200) Using(stmt_address::varchar(200));
Alter Table "near_source_model_layer"."cust-06-30" Alter column e_mail_address Type varchar(50) Using(e_mail_address::varchar(50));
Alter Table "near_source_model_layer"."cust-06-30" Alter column corp_name Type varchar(100) Using(corp_name::varchar(100));
Alter Table "near_source_model_layer"."cust-06-30" Alter column corp_post_code Type varchar(10) Using(corp_post_code::varchar(10));
Alter Table "near_source_model_layer"."cust-06-30" Alter column corp_address Type varchar(200) Using(corp_address::varchar(200));
Alter Table "near_source_model_layer"."cust-06-30" Alter column duty_code Type varchar(2) Using(duty_code::varchar(2));
Alter Table "near_source_model_layer"."cust-06-30" Alter column tech_post_code Type varchar(2) Using(tech_post_code::varchar(2));
Alter Table "near_source_model_layer"."cust-06-30" Alter column industry_class_code Type varchar(2) Using(industry_class_code::varchar(2));
Alter Table "near_source_model_layer"."cust-06-30" Alter column corp_kind_code Type varchar(2) Using(corp_kind_code::varchar(2));
Alter Table "near_source_model_layer"."cust-06-30" Alter column corp_scale_code Type varchar(2) Using(corp_scale_code::varchar(2));
Alter Table "near_source_model_layer"."cust-06-30" Alter column exchange_info_code Type varchar(2) Using(exchange_info_code::varchar(2));
Alter Table "near_source_model_layer"."cust-06-30" Alter column branch_code Type varchar(10) Using(branch_code::varchar(10));
Alter Table "near_source_model_layer"."cust-06-30" Alter column issue_channel_code Type varchar(4) Using(issue_channel_code::varchar(4));
Alter Table "near_source_model_layer"."cust-06-30" Alter column reference_code Type varchar(5) Using(reference_code::varchar(5));
Alter Table "near_source_model_layer"."cust-06-30" Alter column credit_limit Type numeric Using(credit_limit::numeric);
Alter Table "near_source_model_layer"."cust-06-30" Alter column take_cash_limit Type numeric Using(take_cash_limit::numeric);
Alter Table "near_source_model_layer"."cust-06-30" Alter column curr_limit Type numeric Using(curr_limit::numeric);
Alter Table "near_source_model_layer"."cust-06-30" Alter column temp_credit_limit Type numeric Using(temp_credit_limit::numeric);
Alter Table "near_source_model_layer"."cust-06-30" Alter column usable_limit Type numeric Using(usable_limit::numeric);
Alter Table "near_source_model_layer"."cust-06-30" Alter column product_count Type numeric Using(product_count::numeric);
Alter Table "near_source_model_layer"."cust-06-30" Alter column public_private_code Type varchar(3) Using(public_private_code::varchar(3));
Alter Table "near_source_model_layer"."cust-06-30" Alter column employee_flag Type varchar(1) Using(employee_flag::varchar(1));
Alter Table "near_source_model_layer"."cust-06-30" Alter column activity_status_code Type varchar(3) Using(activity_status_code::varchar(3));
Alter Table "near_source_model_layer"."cust-06-30" Alter column cycle_credit_flag Type varchar(1) Using(cycle_credit_flag::varchar(1));
Alter Table "near_source_model_layer"."cust-06-30" Alter column first_open_date Type date Using(first_open_date::date);
Alter Table "near_source_model_layer"."cust-06-30" Alter column first_active_date Type date Using(first_active_date::date);
Alter Table "near_source_model_layer"."cust-06-30" Alter column first_stmt_date Type date Using(first_stmt_date::date);
Alter Table "near_source_model_layer"."cust-06-30" Alter column last_trans_date Type date Using(last_trans_date::date);
Alter Table "near_source_model_layer"."cust-06-30" Alter column defecte_date Type date Using(defecte_date::date);
Alter Table "near_source_model_layer"."cust-06-30" Alter column invalid_date Type date Using(invalid_date::date);
Alter Table "near_source_model_layer"."cust-06-30" Alter column hold_card_days Type numeric Using(hold_card_days::numeric);
Alter Table "near_source_model_layer"."cust-06-30" Alter column overdue_status_code Type char(1) Using(overdue_status_code::char(1));
Alter Table "near_source_model_layer"."cust-06-30" Alter column last_ovdu_stat_code Type varchar(1) Using(last_ovdu_stat_code::varchar(1));
Alter Table "near_source_model_layer"."cust-06-30" Alter column total_overdue_count Type varchar(50) Using(total_overdue_count::varchar(50));
Alter Table "near_source_model_layer"."cust-06-30" Alter column high_acct_bill_code Type char(1) Using(high_acct_bill_code::char(1));
Alter Table "near_source_model_layer"."cust-06-30" Alter column first_brush_date Type varchar(50) Using(first_brush_date::varchar(50));
Alter Table "near_source_model_layer"."cust-06-30" Alter column next_brush_date Type varchar(50) Using(next_brush_date::varchar(50));
Alter Table "near_source_model_layer"."cust-07-31" Alter column cust_id Type varchar(50) Using(cust_id::varchar(50));
Alter Table "near_source_model_layer"."cust-07-31" Alter column cust_name Type varchar(100) Using(cust_name::varchar(100));
Alter Table "near_source_model_layer"."cust-07-31" Alter column gender_code Type varchar(2) Using(gender_code::varchar(2));
Alter Table "near_source_model_layer"."cust-07-31" Alter column birthday Type date Using(birthday::date);
Alter Table "near_source_model_layer"."cust-07-31" Alter column age Type numeric Using(age::numeric);
Alter Table "near_source_model_layer"."cust-07-31" Alter column cert_type_code Type varchar(10) Using(cert_type_code::varchar(10));
Alter Table "near_source_model_layer"."cust-07-31" Alter column cert_no Type varchar(50) Using(cert_no::varchar(50));
Alter Table "near_source_model_layer"."cust-07-31" Alter column education_grade_code Type varchar(2) Using(education_grade_code::varchar(2));
Alter Table "near_source_model_layer"."cust-07-31" Alter column nation_code Type varchar(5) Using(nation_code::varchar(5));
Alter Table "near_source_model_layer"."cust-07-31" Alter column year_income Type numeric Using(year_income::numeric);
Alter Table "near_source_model_layer"."cust-07-31" Alter column marriage_status_code Type varchar(2) Using(marriage_status_code::varchar(2));
Alter Table "near_source_model_layer"."cust-07-31" Alter column house_kind_code Type varchar(2) Using(house_kind_code::varchar(2));
Alter Table "near_source_model_layer"."cust-07-31" Alter column reside_years Type numeric Using(reside_years::numeric);
Alter Table "near_source_model_layer"."cust-07-31" Alter column home_phone Type varchar(50) Using(home_phone::varchar(50));
Alter Table "near_source_model_layer"."cust-07-31" Alter column mobile_phone Type varchar(50) Using(mobile_phone::varchar(50));
Alter Table "near_source_model_layer"."cust-07-31" Alter column corp_phone Type varchar(50) Using(corp_phone::varchar(50));
Alter Table "near_source_model_layer"."cust-07-31" Alter column home_post_code Type varchar(10) Using(home_post_code::varchar(10));
Alter Table "near_source_model_layer"."cust-07-31" Alter column house_address Type varchar(200) Using(house_address::varchar(200));
Alter Table "near_source_model_layer"."cust-07-31" Alter column stmt_post_code Type varchar(10) Using(stmt_post_code::varchar(10));
Alter Table "near_source_model_layer"."cust-07-31" Alter column stmt_address Type varchar(200) Using(stmt_address::varchar(200));
Alter Table "near_source_model_layer"."cust-07-31" Alter column e_mail_address Type varchar(50) Using(e_mail_address::varchar(50));
Alter Table "near_source_model_layer"."cust-07-31" Alter column corp_name Type varchar(100) Using(corp_name::varchar(100));
Alter Table "near_source_model_layer"."cust-07-31" Alter column corp_post_code Type varchar(10) Using(corp_post_code::varchar(10));
Alter Table "near_source_model_layer"."cust-07-31" Alter column corp_address Type varchar(200) Using(corp_address::varchar(200));
Alter Table "near_source_model_layer"."cust-07-31" Alter column duty_code Type varchar(2) Using(duty_code::varchar(2));
Alter Table "near_source_model_layer"."cust-07-31" Alter column tech_post_code Type varchar(2) Using(tech_post_code::varchar(2));
Alter Table "near_source_model_layer"."cust-07-31" Alter column industry_class_code Type varchar(2) Using(industry_class_code::varchar(2));
Alter Table "near_source_model_layer"."cust-07-31" Alter column corp_kind_code Type varchar(2) Using(corp_kind_code::varchar(2));
Alter Table "near_source_model_layer"."cust-07-31" Alter column corp_scale_code Type varchar(2) Using(corp_scale_code::varchar(2));
Alter Table "near_source_model_layer"."cust-07-31" Alter column exchange_info_code Type varchar(2) Using(exchange_info_code::varchar(2));
Alter Table "near_source_model_layer"."cust-07-31" Alter column branch_code Type varchar(10) Using(branch_code::varchar(10));
Alter Table "near_source_model_layer"."cust-07-31" Alter column issue_channel_code Type varchar(4) Using(issue_channel_code::varchar(4));
Alter Table "near_source_model_layer"."cust-07-31" Alter column reference_code Type varchar(5) Using(reference_code::varchar(5));
Alter Table "near_source_model_layer"."cust-07-31" Alter column credit_limit Type numeric Using(credit_limit::numeric);
Alter Table "near_source_model_layer"."cust-07-31" Alter column take_cash_limit Type numeric Using(take_cash_limit::numeric);
Alter Table "near_source_model_layer"."cust-07-31" Alter column curr_limit Type numeric Using(curr_limit::numeric);
Alter Table "near_source_model_layer"."cust-07-31" Alter column temp_credit_limit Type numeric Using(temp_credit_limit::numeric);
Alter Table "near_source_model_layer"."cust-07-31" Alter column usable_limit Type numeric Using(usable_limit::numeric);
Alter Table "near_source_model_layer"."cust-07-31" Alter column product_count Type numeric Using(product_count::numeric);
Alter Table "near_source_model_layer"."cust-07-31" Alter column public_private_code Type varchar(3) Using(public_private_code::varchar(3));
Alter Table "near_source_model_layer"."cust-07-31" Alter column employee_flag Type varchar(1) Using(employee_flag::varchar(1));
Alter Table "near_source_model_layer"."cust-07-31" Alter column activity_status_code Type varchar(3) Using(activity_status_code::varchar(3));
Alter Table "near_source_model_layer"."cust-07-31" Alter column cycle_credit_flag Type varchar(1) Using(cycle_credit_flag::varchar(1));
Alter Table "near_source_model_layer"."cust-07-31" Alter column first_open_date Type date Using(first_open_date::date);
Alter Table "near_source_model_layer"."cust-07-31" Alter column first_active_date Type date Using(first_active_date::date);
Alter Table "near_source_model_layer"."cust-07-31" Alter column first_stmt_date Type date Using(first_stmt_date::date);
Alter Table "near_source_model_layer"."cust-07-31" Alter column last_trans_date Type date Using(last_trans_date::date);
Alter Table "near_source_model_layer"."cust-07-31" Alter column defecte_date Type date Using(defecte_date::date);
Alter Table "near_source_model_layer"."cust-07-31" Alter column invalid_date Type date Using(invalid_date::date);
Alter Table "near_source_model_layer"."cust-07-31" Alter column hold_card_days Type numeric Using(hold_card_days::numeric);
Alter Table "near_source_model_layer"."cust-07-31" Alter column overdue_status_code Type char(1) Using(overdue_status_code::char(1));
Alter Table "near_source_model_layer"."cust-07-31" Alter column last_ovdu_stat_code Type varchar(1) Using(last_ovdu_stat_code::varchar(1));
Alter Table "near_source_model_layer"."cust-07-31" Alter column total_overdue_count Type varchar(50) Using(total_overdue_count::varchar(50));
Alter Table "near_source_model_layer"."cust-07-31" Alter column high_acct_bill_code Type char(1) Using(high_acct_bill_code::char(1));
Alter Table "near_source_model_layer"."cust-07-31" Alter column first_brush_date Type varchar(50) Using(first_brush_date::varchar(50));
Alter Table "near_source_model_layer"."cust-07-31" Alter column next_brush_date Type varchar(50) Using(next_brush_date::varchar(50));
Alter Table "near_source_model_layer"."cust-08-31" Alter column cust_id Type varchar(50) Using(cust_id::varchar(50));
Alter Table "near_source_model_layer"."cust-08-31" Alter column cust_name Type varchar(100) Using(cust_name::varchar(100));
Alter Table "near_source_model_layer"."cust-08-31" Alter column gender_code Type varchar(2) Using(gender_code::varchar(2));
Alter Table "near_source_model_layer"."cust-08-31" Alter column birthday Type date Using(birthday::date);
Alter Table "near_source_model_layer"."cust-08-31" Alter column age Type numeric Using(age::numeric);
Alter Table "near_source_model_layer"."cust-08-31" Alter column cert_type_code Type varchar(10) Using(cert_type_code::varchar(10));
Alter Table "near_source_model_layer"."cust-08-31" Alter column cert_no Type varchar(50) Using(cert_no::varchar(50));
Alter Table "near_source_model_layer"."cust-08-31" Alter column education_grade_code Type varchar(2) Using(education_grade_code::varchar(2));
Alter Table "near_source_model_layer"."cust-08-31" Alter column nation_code Type varchar(5) Using(nation_code::varchar(5));
Alter Table "near_source_model_layer"."cust-08-31" Alter column year_income Type numeric Using(year_income::numeric);
Alter Table "near_source_model_layer"."cust-08-31" Alter column marriage_status_code Type varchar(2) Using(marriage_status_code::varchar(2));
Alter Table "near_source_model_layer"."cust-08-31" Alter column house_kind_code Type varchar(2) Using(house_kind_code::varchar(2));
Alter Table "near_source_model_layer"."cust-08-31" Alter column reside_years Type numeric Using(reside_years::numeric);
Alter Table "near_source_model_layer"."cust-08-31" Alter column home_phone Type varchar(50) Using(home_phone::varchar(50));
Alter Table "near_source_model_layer"."cust-08-31" Alter column mobile_phone Type varchar(50) Using(mobile_phone::varchar(50));
Alter Table "near_source_model_layer"."cust-08-31" Alter column corp_phone Type varchar(50) Using(corp_phone::varchar(50));
Alter Table "near_source_model_layer"."cust-08-31" Alter column home_post_code Type varchar(10) Using(home_post_code::varchar(10));
Alter Table "near_source_model_layer"."cust-08-31" Alter column house_address Type varchar(200) Using(house_address::varchar(200));
Alter Table "near_source_model_layer"."cust-08-31" Alter column stmt_post_code Type varchar(10) Using(stmt_post_code::varchar(10));
Alter Table "near_source_model_layer"."cust-08-31" Alter column stmt_address Type varchar(200) Using(stmt_address::varchar(200));
Alter Table "near_source_model_layer"."cust-08-31" Alter column e_mail_address Type varchar(50) Using(e_mail_address::varchar(50));
Alter Table "near_source_model_layer"."cust-08-31" Alter column corp_name Type varchar(100) Using(corp_name::varchar(100));
Alter Table "near_source_model_layer"."cust-08-31" Alter column corp_post_code Type varchar(10) Using(corp_post_code::varchar(10));
Alter Table "near_source_model_layer"."cust-08-31" Alter column corp_address Type varchar(200) Using(corp_address::varchar(200));
Alter Table "near_source_model_layer"."cust-08-31" Alter column duty_code Type varchar(2) Using(duty_code::varchar(2));
Alter Table "near_source_model_layer"."cust-08-31" Alter column tech_post_code Type varchar(2) Using(tech_post_code::varchar(2));
Alter Table "near_source_model_layer"."cust-08-31" Alter column industry_class_code Type varchar(2) Using(industry_class_code::varchar(2));
Alter Table "near_source_model_layer"."cust-08-31" Alter column corp_kind_code Type varchar(2) Using(corp_kind_code::varchar(2));
Alter Table "near_source_model_layer"."cust-08-31" Alter column corp_scale_code Type varchar(2) Using(corp_scale_code::varchar(2));
Alter Table "near_source_model_layer"."cust-08-31" Alter column exchange_info_code Type varchar(2) Using(exchange_info_code::varchar(2));
Alter Table "near_source_model_layer"."cust-08-31" Alter column branch_code Type varchar(10) Using(branch_code::varchar(10));
Alter Table "near_source_model_layer"."cust-08-31" Alter column issue_channel_code Type varchar(4) Using(issue_channel_code::varchar(4));
Alter Table "near_source_model_layer"."cust-08-31" Alter column reference_code Type varchar(5) Using(reference_code::varchar(5));
Alter Table "near_source_model_layer"."cust-08-31" Alter column credit_limit Type numeric Using(credit_limit::numeric);
Alter Table "near_source_model_layer"."cust-08-31" Alter column take_cash_limit Type numeric Using(take_cash_limit::numeric);
Alter Table "near_source_model_layer"."cust-08-31" Alter column curr_limit Type numeric Using(curr_limit::numeric);
Alter Table "near_source_model_layer"."cust-08-31" Alter column temp_credit_limit Type numeric Using(temp_credit_limit::numeric);
Alter Table "near_source_model_layer"."cust-08-31" Alter column usable_limit Type numeric Using(usable_limit::numeric);
Alter Table "near_source_model_layer"."cust-08-31" Alter column product_count Type numeric Using(product_count::numeric);
Alter Table "near_source_model_layer"."cust-08-31" Alter column public_private_code Type varchar(3) Using(public_private_code::varchar(3));
Alter Table "near_source_model_layer"."cust-08-31" Alter column employee_flag Type varchar(1) Using(employee_flag::varchar(1));
Alter Table "near_source_model_layer"."cust-08-31" Alter column activity_status_code Type varchar(3) Using(activity_status_code::varchar(3));
Alter Table "near_source_model_layer"."cust-08-31" Alter column cycle_credit_flag Type varchar(1) Using(cycle_credit_flag::varchar(1));
Alter Table "near_source_model_layer"."cust-08-31" Alter column first_open_date Type date Using(first_open_date::date);
Alter Table "near_source_model_layer"."cust-08-31" Alter column first_active_date Type date Using(first_active_date::date);
Alter Table "near_source_model_layer"."cust-08-31" Alter column first_stmt_date Type date Using(first_stmt_date::date);
Alter Table "near_source_model_layer"."cust-08-31" Alter column last_trans_date Type date Using(last_trans_date::date);
Alter Table "near_source_model_layer"."cust-08-31" Alter column defecte_date Type date Using(defecte_date::date);
Alter Table "near_source_model_layer"."cust-08-31" Alter column invalid_date Type date Using(invalid_date::date);
Alter Table "near_source_model_layer"."cust-08-31" Alter column hold_card_days Type numeric Using(hold_card_days::numeric);
Alter Table "near_source_model_layer"."cust-08-31" Alter column overdue_status_code Type char(1) Using(overdue_status_code::char(1));
Alter Table "near_source_model_layer"."cust-08-31" Alter column last_ovdu_stat_code Type varchar(1) Using(last_ovdu_stat_code::varchar(1));
Alter Table "near_source_model_layer"."cust-08-31" Alter column total_overdue_count Type varchar(50) Using(total_overdue_count::varchar(50));
Alter Table "near_source_model_layer"."cust-08-31" Alter column high_acct_bill_code Type char(1) Using(high_acct_bill_code::char(1));
Alter Table "near_source_model_layer"."cust-08-31" Alter column first_brush_date Type varchar(50) Using(first_brush_date::varchar(50));
Alter Table "near_source_model_layer"."cust-08-31" Alter column next_brush_date Type varchar(50) Using(next_brush_date::varchar(50));




ENDOFPSQL
close(file);
