my $psql = "psql -a -h localhost -d bank -U postgres";
our ($a)=@ARGV;
$str = substr($a,5,5);
$cust = "cust-".$str;
$card = "card-".$str;
$acct = "acct-".$str;
#经过分析card表满足
open(PSQL,"| $psql");
print PSQL<<END;
set client_encoding=GBK;
create table intergration.PARTY_ADDRESS_INORMATION_TYPE_CODE_T(
	PARTY_ADDRESS_INORMATION_TYPE_CODE VARCHAR(50),
	PARTY_ADDRESS_INORMATION_TYPE VARCHAR(50) 
);

create table intergration.PARTY_ADDRESS_INORMATION_HISTORY(
	PARTY_ID VARCHAR(50),
	PARTY_ADDRESS_INORMATION VARCHAR(50),
	LOADING_DATE  VARCHAR(50)
);


create table intergration.PARTY(
	PARTY_ID VARCHAR(50),
	PUBLIC_PRIVATE_CODE VARCHAR(50),
	CUST_NAME  VARCHAR(50),
	BIRTHDAY   DATE,
	PARTY_START_DT  DATE,
	PARTY_END_DT  DATE,
	GENDER_CODE  VARCHAR(50)
);

create table intergration.PARTY_BUSINESS_COUNT(
	PARTY_ID VARCHAR(50),
	CUST_ID  VARCHAR(50),
	PRODUCT_COUNT  numeric(20,2),
	CARD_COUNT  numeric(20,2),
	PARTY_START_DT  DATE,
	PARTY_END_DT  DATE
);

create table intergration.PARTY_AGREEMENT_RELATION_HISTORY(
	PARTY_ID VARCHAR(50),
	AGREEMENT_ID  VARCHAR(50),
	LOADING_DATE DATE
	
);

create table intergration.ACCOUNT_CUST_RELATION_HISTORY(
	PARTY_ID VARCHAR(50),
	AGREEMENT_ID  VARCHAR(50),
	CUST_ID  VARCHAR(50),
	ACCT_NO  VARCHAR(50),
	LOADING_DATE DATE
);

create table intergration.CUST(
	CUST_ID  VARCHAR(50),
	PARTY_ID VARCHAR(50),
	CUST_NAME  VARCHAR(50),
	BIRTHDAY   DATE,
	AGE    numeric(20,2),
	CERT_NO   VARCHAR(50),
	EDUCATION_GRADE_CODE VARCHAR(50),
	CERT_TYPE_CODE  VARCHAR(50),
	NATION_CODE  VARCHAR(50),
	YEAR_INCOME  numeric(20,2),
	MARRIAGE_STATUS_CODE  VARCHAR(50),
	HOME_PHONE   VARCHAR(50),
	MOBILE_PHONE  VARCHAR(50),
	CORP_PHONE  VARCHAR(50),
	E_MAIL_ADDRESS  VARCHAR(50),
	PUBLIC_PRIVATE_CODE  VARCHAR(50),
	EXCHANGE_INFO_CODE   VARCHAR(50),
	START_DT DATE,
	END_DT DATE
);



create table intergration.EVENT(
	EVENT_TRADE_NO SERIAL,
	EVENT_INTEGRAL  VARCHAR(50),
	TRANS_TERMINAL_NO  numeric(20,2),
	TRANS_DESC   VARCHAR(50),
	MERCHANT_CATEGORY_CODE VARCHAR(50),
	MERCHANT_COUNTRY_CODE  VARCHAR(50),
	MERCHANT_NO  VARCHAR(50),
	DEBIT_CREDIT_FLAG  VARCHAR(50),
	LOGIC_MODEL_CODE  VARCHAR(50),
	PLAN_NO  VARCHAR(50),
	TRANS_CODE   VARCHAR(50),
	INTEGRAL_TYPE_CODE   VARCHAR(50),
	TRANS_REF_NO   VARCHAR(50),
	INI_TRANS_CURRENCY  VARCHAR(50),
	CURRENCY_CONV_CODE  VARCHAR(50),
	EVENT_LOAD_DT DATE
);


create table intergration.AGREEMENT_EVENT_RELATION_HISTORY(
	AGREEMENT_ID VARCHAR(50),
	EVENT_TRADE_NO  VARCHAR(50)
);

create table intergration.AGREEMENT(
	AGREEMENT_ID VARCHAR(50),
	AGREEMENT_NAME  VARCHAR(50),
	AGREEMENT_APPLICATION_NO  VARCHAR(50),
	AGREEMENT_PRODUCT_NO  VARCHAR(50),
	AGREEMENT_SIGNING_DT  DATE,
	AGREEMENT_START_DT   DATE,
	AGREEMENT_END_DT  DATE,
	AGREEMENT_EXPIRATION_DT  DATE,
	AGREEMENT_TYPE_CODE  VARCHAR(50),
	AGREEMENT_CURRENCY_CODE  VARCHAR(50),
	CARD_KIND_CODE  VARCHAR(50),
	ISSUE_CHANNEL_CODE  VARCHAR(50),
	BRANCH_CODE  VARCHAR(50),
	CARD_SEND_TYPE_CODE  VARCHAR(50),
	AGREEMENT_MONEYSOURCE_TYPE_CODE  VARCHAR(50),
	AGREEMENT_OPENACCOUNTMECHANISM_NO  VARCHAR(50),
	AGREEMENT_OPENACCOUNTEMPLOYEE_NO  VARCHAR(50)
);

create table intergration.AGREEMENT_OVERDUE_TIMES_RELATION_HISTORY(
	AGREEMENT_OVERDUE_TIMES_RELATION_HISTORY_CODE SERIAL,
	AGREEMENT_ID  VARCHAR(50),
	AGREEMENT_OVERDUE_TIMES_TYPE VARCHAR(50),
	PRIMARY KEY(AGREEMENT_OVERDUE_TIMES_RELATION_HISTORY_CODE,AGREEMENT_ID,AGREEMENT_OVERDUE_TIMES_TYPE),
	AGREEMENT_OVERDUE_TIMES  VARCHAR(50),
	LAST_OVDU_STAT_CODE VARCHAR(50),
	LAST_OVERDUE_DATE VARCHAR(50),
	AOT_START_DT DATE,
	AOT_END_DT DATE
);

create table intergration.AGREEMENT_OVERDUE_TIMES_TYPE_CODE_T(
	AGREEMENT_OVERDUE_TIMES_TYPE_CODE VARCHAR(50),
	AGREEMENT_OVERDUE_TIMES_TYPE  VARCHAR(50),
	CARD_NO DATE
);

create table intergration.AGREEMENT_STATUS_HISTORY(
	AGREEMENT_STATUS_TYPE_CODE SERIAL,
	AGREEMENT_ID  VARCHAR(50),
	PRIMARY KEY(AGREEMENT_ID,AGREEMENT_STATUS_TYPE_CODE),
	ACCT_STATUS_CODE  VARCHAR(50),
	CARD_STATUS_CODE   VARCHAR(50),
	LOCK_STAT_CODE   VARCHAR(50),
	ASH_START_DT  DATE,
	ASH_END_DT  DATE
);

create table intergration.AGREEMENT_STATUS_TYPE_CODE(
	AGREEMENT_STATUS_TYPE_CODE VARCHAR(50),
	AGREEMENT_STATUS_TYPE  VARCHAR(50)
);

create table intergration.CARD(
	AGREEMENT_ID VARCHAR(50),
	CARD_NO  VARCHAR(50),
	BIN_CODE  VARCHAR(50),
	MASTER_CARD_NO   VARCHAR(50),
	OPEN_CARD_DATE  DATE,
	CANCEL_CARD_DATE  DATE,
	CARD_INVALID_DATE  DATE,
	ACTIVE_DATE  DATE,
	MATURITY_DATE  DATE,
	CARD_ISSUE_DATE  DATE,
	CUST_ID  VARCHAR(50),
	CARD_START_DT DATE,
	CARD_END_DT  DATE
);


create table intergration.ACCOUNT(
	AGREEMENT_ID VARCHAR(50),
	ACCT_NO VARCHAR(50),
	ACCOUNT_INVALID_DATE DATE,
	FIRST_OPEN_DATE DATE,
	FIRST_ACTIVE_DATE DATE,
	REFERENCE_CODE VARCHAR(50),
	AUTO_REPAY_TYPE_CODE VARCHAR(50),
	CANCEL_ACCT_DATE DATE,
	APPLICATION_NO VARCHAR(50),
	ACCOUNT_AGREE_NO VARCHAR(50),
	CUST_ID VARCHAR(50),
	ACCOUNT_START_DT DATE,
	ACCOUNT_END_DT DATE
);


create table intergration.AGREEMENT_ADDRESS(
	ADDRESS_CODE VARCHAR(50),
	ADDRESS  VARCHAR(50)
);

create table intergration.PARTY_EVENT_RELATION_HISTORY(
	PARTY_ID VARCHAR(50),
	EVENT_TRADE_NO  VARCHAR(50),
	LOADING_DATE DATE
);

END
close(PSQL);